//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Orders = new HashSet<Order>();
            this.News = new HashSet<News>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<News> News { get; set; }
    }
}
