//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Font
    {
        public Font()
        {
            this.Texts = new HashSet<Text>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public bool Available { get; set; }
        public string CssName { get; set; }
        public string FileName { get; set; }
    
        public virtual ICollection<Text> Texts { get; set; }
    }
}
