//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int ID { get; set; }
        public int StatusID { get; set; }
        public int SessionID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<System.DateTime> DispatchedDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
