//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRange
    {
        public ProductRange()
        {
            this.ProductColors = new HashSet<ProductColor>();
        }
    
        public int ID { get; set; }
        public int GarmentTypeID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public string Webpage { get; set; }
        public bool Available { get; set; }
    
        public virtual GarmentType GarmentType { get; set; }
        public virtual ICollection<ProductColor> ProductColors { get; set; }
    }
}
