//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductColor
    {
        public ProductColor()
        {
            this.ProductSizes = new HashSet<ProductSize>();
            this.Designs = new HashSet<Design>();
        }
    
        public int ID { get; set; }
        public int ProductRangeID { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public int SortOrder { get; set; }
        public string ImagePath { get; set; }
        public string SupplierCode { get; set; }
    
        public virtual ProductRange ProductRange { get; set; }
        public virtual ICollection<ProductSize> ProductSizes { get; set; }
        public virtual ICollection<Design> Designs { get; set; }
    }
}
