//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int ID { get; set; }
        public int ColorID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public bool Available { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
