//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text
    {
        public int ID { get; set; }
        public int DesignID { get; set; }
        public int VinylColorID { get; set; }
        public int FontID { get; set; }
        public string TextValue { get; set; }
        public double PositionX { get; set; }
        public double PositionY { get; set; }
        public byte Alignment { get; set; }
    
        public virtual Design Design { get; set; }
        public virtual Font Font { get; set; }
        public virtual VinylColor VinylColor { get; set; }
    }
}
